title: The Deep Learning Machinery
subtitle: In Computer Vision
author:
  name: Jean-François Reboud
  email: "jeanfrancois.reboud.gre@gmail.com"
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

repository: jfreboud/jfreboud.github.io
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: JFReboud
    github: jfreboud
    linkedin: jean-françois-reboud-832147161

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

include: [_pages]
