title: Deep Learning Machinery
tagline: Dig deeper into neural networks
logo: /_assets/images/logo/logo.png
description: >-
  Understand the machinery behind deep learning neural networks in computer vision.
  Grasp what is hidden in frameworks such as PyTorch and TensorFlow.
show_excerpts: true

header_pages:
  - _pages/table_of_contents.markdown
  - _pages/about.markdown

author:
  name: Jean-François Reboud
  email: "jeanfrancois.reboud.gre@gmail.com"
disqus:
    shortname: jeanfrancoisreboud

repository: jfreboud/jfreboud.github.io
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: JFReboud
    linkedin: jean-françois-reboud-832147161

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji

include: [_pages, _assets]
