title: The Deep Learning Machinery
author:
  name: Jean-François Reboud
  email: "jeanfrancois.reboud.gre@gmail.com"
disqus:
    shortname: jeanfrancoisreboud
description: >-
  Understand the machinery behind deep-learning models in computer vision.
  Grasp what is hidden by nature in frameworks such as PyTorch and TensorFlow.
  Design a computer vision framework from scratch with intuition.
show_excerpts: true

header_pages:
  - _pages/table_of_contents.markdown
  - _pages/about.markdown

repository: jfreboud/jfreboud.github.io
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: JFReboud
    github: jfreboud
    linkedin: jean-françois-reboud-832147161

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji

include: [_pages, _assets]
